[package]
name = "actix-geo-widget"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
clap = { version = "4.5.13", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
maxminddb = "0.24.0"
serde = { version = "1.0.204", features = ["derive"] }
