[package]
name = "geoclient"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = { version = "4", features = ["openssl"] }
openssl = { version = "0.10" }
serde = { version = "1.0", features = ["derive"] }
maxminddb = "0.17"
