[package]
name = "actix-geo-widget"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-web-prom = "0.9.0"
chrono = "0.4.38"
clap = { version = "4.5.19", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
maxminddb = "0.24.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
