---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geo-widget
  namespace: geo-widget
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi