---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: geo-widget
  namespace: geo-widget
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/data/geo-widget"
