name: Dockerfile Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile

    - name: build container but do not push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false