name: Dockerfile Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:

    ## https://github.com/actions/checkout
    - uses: actions/checkout@v7

    ## https://github.com/hadolint/hadolint-action
    - uses: hadolint/hadolint-action@v3
      with:
        dockerfile: Dockerfile
        verbose: true

    ## https://github.com/docker/build-push-action
    - name: build container but do not push
      uses: docker/build-push-action@v7
      with:
        context: .
        file: ./Dockerfile
        push: false