name: Rust Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Check format
      run: make format

    - name: Chek lint
      run: make lint

    - name: Build
      run: cargo build --verbose

    - name: Get databases
      env:
        MAXMIND_API_KEY: ${{ secrets.MAXMIND_API_KEY }}
      run: bash get_maxmind_database.sh -u -e GeoLite2-ASN,GeoLite2-City -k "${MAXMIND_API_KEY}"

    - name: Run tests
      run: make test
