name: Rust

on:
  ## Limit to manual run for now
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

    - name: Get maxmind database
      env:
        MAXMIND_API_KEY: ${{ secrets.MAXMIND_API_KEY }}
      run: bash get_maxmind_database.sh -u -e GeoLite2-ASN,GeoLite2-City -k "${MAXMIND_API_KEY}"

    - name: Run tests
      run: cargo test --verbose
